### ISSUE TITLE
Suggestions for using ChEMBL-Downloader

### ISSUE THREAD

**Issue by cthoyt** [jhylin/Data_in_life_blog#1]
Great to see you're using chembl-downloader in https://jhylin.github.io/Data_in_life_blog/posts/17_ML2-2_Random_forest/2_random_forest_classifier.html! I have a few suggestions to take your reproducibility to the next level.

## Generating SQL

```python
# Query chembl_downloader to show SQL required 
# to extract ChEMBL data for a specific protein target
# e.g. target_chembl_id for acetylcholinesterase (AChE): CHEMBL220
queries.markdown(queries.get_target_sql(target_id="CHEMBL220", target_type="SINGLE PROTEIN"))
```

The `queries.get_target_sql` actually generates a string that represents the SQL. I saw in the next cell, you re-define this explicitly. I'd suggest you change this cell to 

```python
# Generate SQL for a query on the given target_id
# for acetylcholinesterase (AChE): CHEMBL220
sql = queries.get_target_sql(target_id="CHEMBL220", target_type="SINGLE PROTEIN")

# Pretty-print the SQL in Jupyter
queries.markdown(sql)
```

Then, you don't have to redefine it in the next cell by hand!

## Querying

The following 3 cells in a row (paraphrased) are about actually running the query and getting the data. There's a more reproducible way that doesn't require commenting out code, which means that anyone can re-run the notebook:

```python
df = chembl_downloader.query(sql)

...

# Save df as .csv file (uncomment last line to run)
#df.to_csv("chembl_d_ache", sep=",", index=False)

...

# Load dataset from saved .csv file
df_ache = pd.read_csv("chembl_d_ache")
print(df_ache.shape)
df_ache.head()
```

Try it like this:

```python
from pathlib import Path

# Pick any directory, but make sure it's relative to your home directory
directory = Path.home().joinpath(".data", "blog")
# Create the directory if it doesn't exist
directory.mkdir(exist_okay=True, parents=True)

# Create a file path that corresponds to the version, since this could change
path = directory.joinpath(f"chembl_d_ache_{latest_version}.tsv")

if path.is_file():
    # If the file already exists, load it
    df_ache = pd.read_csv(path, sep=',')
else:
    # If the file doesn't already exist, make the query then cache it
    df_ache = chembl_downloader.query(sql)
    df_ache.to_csv(path, sep=",", index=False)
```

**Comment by jhylin** [comment]
@cthoyt I tried the suggested code for generating SQL, but it didn't turn out to be exactly what I wanted, I then realised the reason I've entered the SQL by hand was so that I could add an extra line - MOLECULE_DICTIONARY.max_phase (which was not included in the original queries.get_target_sql), in order to get the max_phase for the compounds. Is there any other way to do this? (unless I've missed something...)

I have updated the querying part as suggested, which was very handy indeed, I'll certainly use this method for future ChEMBL data querying and saving. Thanks for taking the time to respond, always glad to learn new tricks for better code!

**Comment by cthoyt** [comment]
Aha! I missed that while reading before. It would be helpful to the reader to make sure that the query you show with markdown and the one you actually run are the same, so there are a few options:

1. We could add the line for returning the max phase into https://github.com/cthoyt/chembl-downloader/blob/b3dc6a57a9d8b21e5b1c87b9552954e57dd97c00/src/chembl_downloader/queries.py#L93-L131 (either as a default, or togglable). Might be a fun chance for you to try making a PR on a repo that you use for your blog, and I'm sure it would make a really interesting blog post to talk about how you actually go about making upstream contributions! Would be happy to help you work though this.
2. You can simply write your SQL query by hand and not show the auto-generated one. You can still reuse the `queries.markdown` function - it's a simple wrapper for highlighting SQL code

**Comment by jhylin** [comment]
Oh yes, it'll be great to add max_phase as a togglable option, and also a good thing for me to start contributing to open-source projects. Is it best if I fork the chembl_downloader repo and go from there (e.g. add extra code as a PR)? In the meantime, I think I'll leave out the auto-generated one to avoid confusion. Thanks for providing guidance, much appreciated.

**Comment by cthoyt** [comment]
Yes, fork + PR would be great! Let me know if you run into any issues

**Comment by jhylin** [comment]
@cthoyt I've sent a PR to the upstream repo, hopefully it's not too far off from the expected (not very experienced with PR obviously). If I need to do anything further, please let me know. Thanks
